ledger:
  fee-rate: 0.031
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ledger
    username: postgres
    password: 12345678
  jpa:
    hibernate:
      ddl-auto: none
  sql:
    init:
      mode: always
  threads:
    virtual:
      enabled: true